matching_groups:
  - /admin/user/[0-9]{10}
  - /user/[0-9]+/present/receive
  - /user/[0-9]+/present/index/[0-9]+
  - /user/[0-9]+/card/addexp/[0-9]+
  - /user/[0-9]+/gacha/draw/[0-9]+/[0-9]+
  - /user/[0-9]+/gacha/index
  - /user/[0-9]+/reward
  - /user/[0-9]+/card
  - /user/[0-9]+/item
  - /user/[0-9]+/home

sort: avg
reverse: true
metrics:
  - count
  - method
  - uri
  - min
  - avg
  - max
  - sum
file: /var/log/nginx/access.ndjson
