matching_groups:
  - /admin/user/[0-9]{10}
  - /user/[0-9]{10}/present/receive
  - /user/[0-9]{10}/present/index/[0-9]+
  - /user/[0-9]{10}/card/addexp/[0-9]+
  - /user/[0-9]{10}/gacha/draw/[0-9]+/[0-9]+
  - /user/[0-9]{10}/gacha/index
  - /user/[0-9]{10}/reward
  - /user/[0-9]{10}/card
  - /user/[0-9]{10}/item
  - /user/[0-9]{10}/home
  - /user/[0-9]{4}/present/receive
  - /user/[0-9]{4}/present/index/[0-9]+
  - /user/[0-9]{4}/card/addexp/[0-9]+
  - /user/[0-9]{4}/gacha/draw/[0-9]+/[0-9]+
  - /user/[0-9]{4}/gacha/index
  - /user/[0-9]{4}/reward
  - /user/[0-9]{4}/card
  - /user/[0-9]{4}/item
  - /user/[0-9]{4}/home
  
sort: avg
reverse: true
metrics:
  - count
  - method
  - uri
  - min
  - avg
  - max
  - sum
file: /var/log/nginx/access.ndjson
